"""add deleted_at to secrets

Revision ID: b7981284763f
Revises: 412ab868f224
Create Date: 2026-07-15 08:17:33.162071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7981284763f'
down_revision: Union[str, Sequence[str], None] = '412ab868f224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('secret_versions_secret_id_fkey'), 'secret_versions', type_='foreignkey')
    op.create_foreign_key(None, 'secret_versions', 'secrets', ['secret_id'], ['id'])
    op.add_column('secrets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secrets', 'deleted_at')
    op.drop_constraint(None, 'secret_versions', type_='foreignkey')
    op.create_foreign_key(op.f('secret_versions_secret_id_fkey'), 'secret_versions', 'secrets', ['secret_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
